connection_mode = "Tcp"
ip = "192.168.31.88"
port = 54345
phone_ip = "192.168.31.17"
adb_port = 5555
audio_format = "f32"
channel_count = "Stereo"
sample_rate = "48000"
device_id = "BlackHole2ch_UID"
start_at_login = false
start_minimized = false
auto_connect = false
denoise = false
denoise_kind = "Rnnoise"
speex_noise_suppress = -30
speex_vad_enabled = false
speex_vad_threshold = 80
speex_agc_enabled = false
speex_agc_target = 8000
speex_dereverb_enabled = false
speex_dereverb_level = 0.5
theme = "System"
amplify = false
amplify_value = 2.0
post_effect = "NoEffect"
